### ISSUE TITLE
Wait for imu data 

### ISSUE THREAD

**Issue by shenglunch** [gaowenliang/imu_utils#15]
Hello Gao，
May I ask you a question？After run launch file，“wait for imu data” will appear. I check topic information(rostopic list  & rostopic inof /xx), there is not any problem. 
Thank you very much！

**Comment by johnjin404** [comment]
you need to wait for the bad file playing end,,look at the imu_an.cpp.

**Comment by csl1994** [comment]
thanks！

**Comment by shenglunch** [comment]
> you need to wait for the bad file playing end,,look at the imu_an.cpp.
thanks!

**Comment by maxwu8416** [comment]
@csl1994 hay~ i also have same problem as you did. do you solved the problem ? @johnjin404  i already your suggest  try to wait for bag file playing until the end but nothing change. is it need to do it at the same time ? (playing bag file and do roslaunch) or play the bag file before do roslaunch ? both of them i already try it but still the same. if you have any idea ill be really grateful.

**Comment by shenglunch** [comment]
> @csl1994 hay~ i also have same problem as you did. do you solved the problem ? @johnjin404 i already your suggest try to wait for bag file playing until the end but nothing change. is it need to do it at the same time ? (playing bag file and do roslaunch) or play the bag file before do roslaunch ? both of them i already try it but still the same. if you have any idea ill be really grateful.

**Comment by shenglunch** [comment]
@maxwu8416 I think the parameter("max_time_min") means that the bag file should be played for xxx minutes, so I changed it to 1 minute and it will be finished soon, but it will remind me that "the time is too short".finally i run imu for 40 m, and set the  parameter as follow
`<param name="max_time_min" type="int" value= "30"/>`

**Comment by maxwu8416** [comment]
Okay~ seems worth to try ! Thx for ur reply ! I’ll try it later and update the info

**Comment by foemre** [comment]
It seems that the program doesn't give useful feedback about whether it receives imu info. But it does. So if you cannot be sure, just change `max_time_min` in your launch file to 1 min or so, and see the results. But for accurate results you have to at least run it for about 2 hours.

**Comment by SyahirMuzni** [comment]
Hi, I am facing the same problem here. How am I going to configure the duration of the data recording? I recorded a rosbag for 1 minute. I did make some changes in the *launch file & imu_an.cpp*.
![Screenshot from 2022-10-12 16-19-50](https://user-images.githubusercontent.com/94072577/195308875-02eb649b-9aed-4ee3-9e71-dd561ba795c2.png)
![Screenshot from 2022-10-12 17-42-20](https://user-images.githubusercontent.com/94072577/195309372-5e4ba012-88b0-49b3-82a0-fee1548188b4.png)

But the recording is still too short. Where and how should I change the parameters? FYI, I am still new in cpp. 

Thank you so much for your help!

**Comment by tulingcheng86** [comment]
> @maxwu8416我认为参数(“max_time_min”)的意思是bag文件要播放xxx分钟，所以我把它改成1分钟，很快就播放完了，但它会提醒我“时间太短”。最后我运行imu 40 m，参数设置如下 `<param name="max_time_min" type="int" value= "30"/>`

THINKS! IT HELPFUL!

**Comment by tulingcheng86** [comment]
> @maxwu8416我认为参数(“max_time_min”)的意思是bag文件要播放xxx分钟，所以我把它改成1分钟，很快就播放完了，但它会提醒我“时间太短”。最后我运行imu 40 m，参数设置如下 `<param name="max_time_min" type="int" value= "30"/>`

有用！

**Comment by wells-sde** [comment]
> > @maxwu8416我认为参数(“max_time_min”)的意思是bag文件要播放xxx分钟，所以我把它改成1分钟，很快就播放完了，但它会提醒我“时间太短”。最后我运行imu 40 m，参数设置如下 `<param name="max_time_min" type="int" value= "30"/>`
> 
> THINKS! IT HELPFUL!

你帧的需要等30分钟吗，还是只要imu bag 播放完了就可以计算参数了？
