### ISSUE TITLE
Dataset Duration

### ISSUE THREAD

**Issue by zgxsin** [gaowenliang/imu_utils#18]
Is it a hard requirement that we should have a rosbag of 2-hour duration?
Do that matter a lot?

**Comment by ferreram** [comment]
If you need to estimate accurately your IMU biases, you should even have a longer ROS bag (like 10 hours or so). Also make sure that the IMU is completely still while recording the data (no vibration around or anything) and try to put it somewhere with constant temperature.

**Comment by zgxsin** [comment]
Thank you!
