### ISSUE TITLE
imu measurement rate and rosbag play rate 

### ISSUE THREAD

**Issue by mmp52** [gaowenliang/imu_utils#19]
Hello @gaowenliang ,

My imu works on 50 hz, if I record the values on my rosbag I can see that recording happens not exactly at 50hz, so in order to work on this algorithm shoud I play rosbag with rosbag play -r mybagfile.bag anyway, or should I directly play it without indicating the frequency?
Also, does this algorithm work on only 200 hz or some other frequencies as well, if so should I give the frequency of my IMU as an input to the system somewhere?

Thanks,
Metin

**Comment by tianxinyu0509** [comment]
@mmp52 Regardless of the frequency of the imu, ros sends an imu message with a timestamp.The code is processed based on this timestamp. Directly play it without indicating the frequency.

**Comment by mmp52** [comment]
@tianxinyu0509 Thank you very much!
