### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by kxhappy** [gaowenliang/imu_utils#25]
运行时，终端一直是wait for imu data.我已经正确的订阅了imu的话题。

**Comment by jarvisyjw** [comment]
问题解决了么？

**Comment by Sherlock-hh** [comment]
俺也想问🙏，因为为我看大佬的read me写的是：roabag play -r 200 ，200倍播放的话我录了50分钟的视频一分钟不到就放完了，但是一直现实wait for imu data，所以我也不明白到底是要怎样录了，是录个50*200 分钟的视频还是把-r 200去了，还是有别的方法？

**Comment by haoxinnihao** [comment]
> 俺也想问🙏，因为为我看大佬的read me写的是：roabag play -r 200 ，200倍播放的话我录了50分钟的视频一分钟不到就放完了，但是一直现实wait for imu data，所以我也不明白到底是要怎样录了，是录个50*200 分钟的视频还是把-r 200去了，还是有别的方法？

我也遇到了这个问题，请问你解决了吗？

**Comment by Sherlock-hh** [comment]
@haoxinnihao 抱歉，忘了

**Comment by qinqi-mm** [comment]
> > 俺也想问🙏，因为为我看大佬的read me写的是：roabag play -r 200 ，200倍播放的话我录了50分钟的视频一分钟不到就放完了，但是一直现实wait for imu data，所以我也不明白到底是要怎样录了，是录个50*200 分钟的视频还是把-r 200去了，还是有别的方法？
> 
> 我也遇到了这个问题，请问你解决了吗？

大佬请问解决了吗？我也遇到了这个问题
